version: '3.9'

services:

  os-manager-back:
    build: .
    container_name: os-manager
    restart: always
    entrypoint: sleep infinity
    ports: 
      - 3333:3333
    depends_on:
      - redis
      - rabbitmq
    links:
      - redis
      - rabbitmq
    environment:
      JWT_SECRET: secret
      RESET_PASSWORD_SECRET: secret
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EMAIL_USERNAME: 7c120fba39e28b
      EMAIL_PASSWORD: 80ac73b879dcf6
      EMAIL_PORT: 2525
      EMAIL_HOST: sandbox.smtp.mailtrap.io
    volumes:
      - .:/app


  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data/redis


  rabbitmq:
    image: rabbitmq:3.6.6-management
    container_name: rabbitmq
    ports: 
      - 25672:25672
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = passw123
    restart: always